### ISSUE TITLE
Parsing the extern failed

### ISSUE THREAD

**Issue by user471** [kRITZCREEK/psc-ide#101]
psc 0.8
```
module Main where
foo = {x: {y: 1}}
```
```
{"efExports":[{"ValueRef":{"Ident":"foo"}}],"efImports":[{"eiImportedAs":null,"eiModule":[{"runProperName":"Prim"}],"eiImportType":{"Implicit":true}}],"efVersion":"0.8.0.0","efDeclarations":[{"EDValue":{"edValueType":{"tag":"TypeApp","contents":[{"tag":"TypeConstructor","contents":"Prim.Object"},{"tag":"RCons","contents":["x",{"tag":"TypeApp","contents":[{"tag":"TypeConstructor","contents":"Prim.Object"},{"tag":"RCons","contents":["y",{"tag":"TypeConstructor","contents":"Prim.Int"},{"tag":"REmpty","contents":[]}]}]},{"tag":"REmpty","contents":[]}]}]},"edValueName":{"Ident":"foo"}}}],"efFixities":[],"efModuleName":[{"runProperName":"Main"}]}
```

```
{"command":"load","params":{"modules":[],"dependencies":["Main"]}}
Answer was: Left (GeneralError "Parsing the extern at: c:\\prog\\ps\\test2\\output\\Main\\externs.json failed")
```

**Comment by nwolverson** [comment]
What psc-ide version are you using? With 0.8 compiler an updated version has to be used, these changes haven't been merged https://github.com/kRITZCREEK/psc-ide/pull/98

**Comment by user471** [comment]
I use latest released version 0.5.0. I guess I need to build master version

**Comment by nwolverson** [comment]
Incorrect, the changes are not merged into master, you would have to build the branch from that PR. Obviously a new release will be made when 0.8 is released.

**Comment by user471** [comment]
>Obviously a new release will be made when 0.8 is released.

I don't think it would hurt anyone if psc-ide has release compatible with psc 0.8 RC.
Also, release note should mention what version of psc is supported.

**Comment by kRITZCREEK** [comment]
We can't make a psc-ide release for a non-released purescript version. It will not build on stackage, because there is no compatible purescript version on hackage.
If you want to build a psc-ide exectuable that works with the latest master you'll need to:
- clone both `psc-ide` and `purescript`
- edit stack.yaml "packages" field to point to the cloned `purescript` repository
- `stack install`

This will install both a new purescript compiler and a psc-ide version that is compatible with it.

**Comment by user471** [comment]
>It will not build on stackage, because there is no compatible purescript version on hackage.

Isn't release just an archive with binaries? Why is it depend on purescript? 
stack doesn't work on my machine.

**Comment by user471** [comment]
Could someone just build window binaries and put it anywhere so it would be available to download?

**Comment by kRITZCREEK** [comment]
@user471 What version are you currently on, v0.8.0-rc1? I need to know because it's incompatible with the current master when I build binaries for you.

**Comment by user471** [comment]
rc1

**Comment by kRITZCREEK** [comment]
@user471 https://www.dropbox.com/s/02lcs9hf229ydto/psc-ide-v0.8.0-rc1.zip?dl=0 <- If you trust me :D

**Comment by user471** [comment]
Thanks. Is it possible to use cabal instead of stack to build psc-ide from source?

**Comment by kRITZCREEK** [comment]
Yes it is. The versions are just not locked down in the .cabal file so you'd need to grab the right [stackage config file](https://www.stackage.org/lts-3.15/cabal.config).

 Right now you'd also need to pull in the purescript source files because the release candidate is not uploaded to hackage.
