### ISSUE TITLE
psc-ide-server doesn't return answer

### ISSUE THREAD

**Issue by user471** [kRITZCREEK/psc-ide#102]
The same project https://github.com/kRITZCREEK/psc-ide/issues/101
```
{"command":"type","params":{"filters":[{"filter":"modules","params":{"modules":null}}],"search":"foo"}}
{"command":"type","params":{"filters":[{"filter":"modules","params":{"modules":null}}],"search":"foo"}}
```

**Comment by kRITZCREEK** [comment]
The server needs to be able to parse the externs files before it can answer the `type` command.
 We'll need to wait for an official purescript release before releasing a new psc-ide.

**Comment by user471** [comment]
>The server needs to be able to parse the externs files before it can answer the type command.
Could it answer an error instead of silence?

**Comment by kRITZCREEK** [comment]
It will probably answer with an empty array currently. You will get error messages when loading the incompatible externs files.
