### ISSUE TITLE
Check source text

### ISSUE THREAD

**Issue by user471** [kRITZCREEK/psc-ide#112]
```
{
  "command": "check",
  "params": {
    "source": "module Main where x ="
  }
}
```
The editor could use it to show current errors in file.
The simplest version would only return parsing errors. 
Maybe it could also return typecheck errors, but only if it wouldn't be too slow.

**Comment by kRITZCREEK** [comment]
This is basically running the compiler. With it's new --json-errors flag it has well formed output for editor plugins to pick up. I don't think this is in scope for `psc-ide`. If there is anything that extends running the compiler you can reopen and we can talk about it.

**Comment by user471** [comment]
1) You cannot use compiler for getting only parsing errors.
2) You cannot disable code generation
3) You cannot use compiler to check source text (you can only compiler files, so you need to save file before compilation)

**Comment by user471** [comment]
The main goal of this command is checking code on the fly, when you are typing, without saving the file.

**Comment by kRITZCREEK** [comment]
1) If there are parse errors the compiler won't continue and you'll get the parse errors right away.
2) I don't think running the compiler on a single file is going to create much overhead from codegen since it won't typecheck unless you are not importing anything. We avoid running the typechecker however, but I'm not sure how much time this would save us on a single file.
3) I could see how that is useful. But putting the entire file content into json and sending it linebuffered through a socket will likely be slower than reading a file.

**Comment by user471** [comment]
1) Yes, but if there isn't any parsing errors it would start doing other compilation steps and there isn't any way to prevent it.
2)
> I don't think running the compiler on a single file 

What do you mean? You cannot just running the compiler on a single file, you need to compile the whole project.

**Comment by kRITZCREEK** [comment]
Sure you can. It will give you type errors for the other missing modules but you can just pass the single file to psc. If you get type errors or no errors you can be sure that your module parsed correctly.

**Comment by user471** [comment]
Hm, yes it could work, but you still need to work with file and the main goal is working with text.

**Comment by kRITZCREEK** [comment]
I think we should try to use the compiler first and if that is not fast enough we can try alternatives.

**Comment by user471** [comment]
Do you suggest automatically save file while you are typing and run `psc` over it?

**Comment by kRITZCREEK** [comment]
that. Or using a tempfile.

**Comment by bsermons** [comment]
This is what flycheck already does so no use in reinventing the wheel there. You can see the options here that it supports sending buffer or using temp file:  http://www.flycheck.org/manual/latest/Defining-syntax-checkers.html#Defining-syntax-checkers

Do you find flycheck to be very slow with how it works?  I wonder if it would be an option to have psc have have a standard input option for compiling the main file.

**Comment by kRITZCREEK** [comment]
Rebuild is fast and solves this
