### ISSUE TITLE
Release v0.6.0 binary for mac

### ISSUE THREAD

**Issue by jchayat** [kRITZCREEK/psc-ide#119]
There seems to have been one for 0.5.0 but not for the new version.

Thanks :-)

**Comment by kRITZCREEK** [comment]
The problem is that I need to ask someone with a Mac to build them for me since I don't have one... :D I'll ask on irc later

**Comment by jchayat** [comment]
Just built it. 

Would you like me to send you an archive?

**Comment by kRITZCREEK** [comment]
@paf31 built binaries and even provided a buildscript in  #120 for non-stack users!
