### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by dbushenko** [kRITZCREEK/psc-ide#2]
I follow the steps from the readme. Also (with pulp) I have crated a fresh purescript project, Main.purs looks like this: 

module Main where

import Control.Monad.Eff.Console

my = "hello"

main = do
  log "Hello sailor!"

Then I do the following:

dim@Aldan-3L ~/W/psc-ide-master> stack exec -- psc-ide ../purstest/src/Main.purs
Insert the function name to look for:
main
Right Nothing

dim@Aldan-3L ~/W/psc-ide-master> stack exec -- psc-ide ../purstest/src/Main.purs
Insert the function name to look for:
my
Right Nothing

I can't get any response except 'Right Nothing'

**Comment by kRITZCREEK** [comment]
psc-ide needs the externs.purs files for type lookup. If you run `pulp build` you should get an `output/` folder in your project. Inside of that folder look for your module and pass the path to it's externs.purs file to psc-ide.

Given your current module the path should be `../purstest/output/Main/externs.purs`

**Comment by dbushenko** [comment]
Looks working
