### ISSUE TITLE
Provide 'jump to definition' functionality

### ISSUE THREAD

**Issue by epost** [kRITZCREEK/psc-ide#24]
We want to be able to query for source locations. Note that psc-doc generates TAGS files.

**Comment by kRITZCREEK** [comment]
Most editors can use TAG files out of the box right? I would be nice to have the editor plugins invoke psc-docs to generate the TAG files though.

**Comment by dbushenko** [comment]
Yes, TAGS would be OK solution.

**Comment by kRITZCREEK** [comment]
this one's done
