### ISSUE TITLE
Odd error output

### ISSUE THREAD

**Issue by nwolverson** [kRITZCREEK/psc-ide#33]
Unparseable command (e.g. not enough arguments) in `psc-ide` client gives an error like `"(line 1, column 11):"` (including the quotes).

**Comment by nwolverson** [comment]
Sorry think this is addressed by #32 ...

**Comment by kRITZCREEK** [comment]
Yeah Parsec does format it's error messages nicely. Before that PR just the first line was taken.

Could you confirm that it works for you?

**Comment by nwolverson** [comment]
I now see:

    Failed to parse command 'typeLookup' with error: "(line 1, column 11):\nunexpected end of input\nexpecting white space"

Bit strange quoted error but you get the point I guess.

**Comment by kRITZCREEK** [comment]
Yeah since it's linebased output I can't unescape the newlines^^
