### ISSUE TITLE
Provide support for managing imports

### ISSUE THREAD

**Issue by kRITZCREEK** [kRITZCREEK/psc-ide#72]
- [x] Parse module imports
- [ ] Remove unused imports
- [ ] Add import when the user completes an unimported identifier
- [ ] Allow adding/removing qualifiers from module imports.
  - [ ] When adding a qualifier qualify all the used methods in the file
  - [ ] When removing a qualifier remove all qualifications and build a new import list for the unqualified module

**Comment by kRITZCREEK** [comment]
Branch use-ps-parser does now use the PureScript Parser to get all the imports for a given file.

Next up is traversing the AST to see if there is unused imports.

**Comment by nwolverson** [comment]
I'd love to remove the ugly imports parsing in the atom package. Currently I'm keeping a list of the imports and the qualified imports to enable completion; explicit imports are a bit of an issue.

On unused imports, I was just looking at adding a warning to the purescript compiler about this, there's an issue here already https://github.com/purescript/purescript/issues/1392 - but remove unused is of course what is wanted (I like the style of graying out unused imports & having a 1-button fix)

**Comment by kRITZCREEK** [comment]
I tallked a bit about this with paf31 and he told me to rather wait for garyb to implement the warning and then use the warning messages to provide this information through psc-ide.

Parsing and listing the imports for a given file however is trivial using the PureScript parser and I can definitely provide an endpoint for this. I'll explore around the PureScript AST a bit more and report back!

**Comment by kRITZCREEK** [comment]
Done "enough"
