### ISSUE TITLE
Migrate to 0.7.5 JSON Externs

### ISSUE THREAD

**Issue by kRITZCREEK** [kRITZCREEK/psc-ide#74]

**Comment by kRITZCREEK** [comment]
I'd love to get started on this but I rather wait until purescript-0.7.5 lands on stackage so I can depend on it instead of using a local checkout.

**Comment by kRITZCREEK** [comment]
I've got this working on #76. It would be nice if you could try this out and see if it gives you any trouble @nwolverson @epost.

I'm not quite sure how to proceed. Should I hide 0.7.5 compatibility behind a flag for now or should I just say that the psc-ide releases from now and onward are only purescript >= 0.7.5 compatible?

**Comment by kRITZCREEK** [comment]
One nice sideeffect of this is, that we can now complete data contructors :)

**Comment by nwolverson** [comment]
Seems like the output from `psc-ide` (list imports) now gives the raw module `Show` output rather than the module names as I think it was before? Think you need to `runModuleName`.

    "ModuleName [ProperName {runProperName = \"Prelude\"}]"

**Comment by kRITZCREEK** [comment]
Oh thanks for pointing that out! I'll fix that tomorrow and add a test.

**Comment by kRITZCREEK** [comment]
Should be fixed :)

**Comment by nwolverson** [comment]
Yes LGTM.

**Comment by kRITZCREEK** [comment]
I moved some more code around and released the result as v0.4.0

I can't yet put the release onto hackage because stackage will complain that my project doesn't build with purescript 0.7.4 which is the current version of purescript in stackage,

I guess it's still nice to have 0.7.5 support out there for people on the bleeding edge :)
