### ISSUE TITLE
Add Info command

### ISSUE THREAD

**Issue by kRITZCREEK** [kRITZCREEK/psc-ide#78]
Add info command to psci. Similar like info in ghc-mod.

info <file> <identifier>

This command would make it easier to get nice IDE support for Purescript.

Most important information would be definition and module where identifier is defined. Nice to have is for example list of instances in case identifier is type class.

Copied from https://github.com/purescript/purescript/issues/1053

**Comment by paf31** [comment]
Duplicate?

**Comment by kRITZCREEK** [comment]
Sure
