### ISSUE TITLE
Fewer stringly types, more structure?

### ISSUE THREAD

**Issue by epost** [kRITZCREEK/psc-ide#80]
Thinking about https://github.com/kRITZCREEK/psc-ide/pull/79 some more, we've gone from:

    "Data.Array,Control.Monad" :: String

to:

    ["Data.Array", "Control.Monad"] :: [String]

which I think is a big improvement. Since (I would assume) we all have little love for stringly typed data, why not go the whole hog, and make it

    [["Data","Array"], ["Control","Monad"]] :: [[String]]

instead? We could do something similar for type signatures. One advantage of this, which is where I'm coming from atm, is wrt things like code generation, documentation and tool interop.

As a side note, I've been playing with some json-schema: https://gist.github.com/epost/4a3a04046a94139b2ab1 to try and capture some of the protocol. There are many tools for this sort of thing, including code generators from Haskell ADTs to JSON-schema, and back to TypeScript types for example: http://json-schema.org/implementations.html.

**Comment by kRITZCREEK** [comment]
Just cleaning up my issues. We'll do this in the purescript compiler repo when the need arises
