### ISSUE TITLE
Module 'Main' not found.

### ISSUE THREAD

**Issue by LukaHorvat** [kRITZCREEK/psc-ide#85]
I have an almost empty project made with `pulp init`. I've built it with `pulp build` and there's a Main folder in the output folder and it has the externs.json file in it.

I ran the server in the project root and then ran the client. 

```
C:\Users\Luka\Documents\Projects\SM>psc-ide -p 4000
{"command":"load","params":{"dependencies":["Main"]}}
{"result":"Module 'Main' not found.","resultType":"error"}
```

When I ask about the pwd it correctly reports the project root.

I'm running Windows 10 64bit if that matters at all. All the tools here are installed today so they're the latest available.

**Comment by kRITZCREEK** [comment]
I can take a look next week. If you have a working haskell installation could you try building the current master and see if that fails too?

**Comment by LukaHorvat** [comment]
Compiling from master did the trick. I suppose this is an error on my part because the ide-purescript package did mention I need 0.4 for PSC 0.7.5, but I just assumed that I'd get that version by installing from stack.

**Comment by kRITZCREEK** [comment]
yeah I should have mentioned that in the README... I couldn't upload it to hackage at the time because the newest version of the purescript compiler wasn't in stackage yet. I'll fix this thanks for the report!
