### ISSUE TITLE
Include exported modules with completions

### ISSUE THREAD

**Issue by bsermons** [kRITZCREEK/psc-ide#90]
Not sure if this is a duplicate of #41, if it is then please close this.

I noticed that some completion candidates are not being included in the list when they are exposed as modules.  For example here:
https://github.com/slamdata/purescript-halogen/blob/50c06d684d34592fc19007bb77a618ca9a847f8b/src/Halogen/HTML/Events/Indexed.purs

The `module ExposedEvents` at the bottom includes the items `input` and `input_` and don't come over in the completion list.

**Comment by kRITZCREEK** [comment]
The current resolution algorithm for reexports([Reexports.hs](https://github.com/kRITZCREEK/psc-ide/blob/9de583d4a335aa38945979a14f493e7f53ab4027/lib/PureScript/Ide/Reexports.hs)) does only support exporting a module by it's original name.

It's a little unfortunate that we have to reproduce the entire reexport spec inside psc-ide. But it's absolutely doable.

**Comment by bsermons** [comment]
Yea I agree and I'm not even sure how prevalent that feature is used.  It just caught me off guard since I was testing completions on a module that happened to use it.

**Comment by kRITZCREEK** [comment]
There is more pathological cases... You can for example do this:

```haskell

module Lol where
(
module C
)

import qualified A as C
import qualified B as C

```

And have it export both A and B...

**Comment by kRITZCREEK** [comment]
can we call this fixed? We are not yet tracking selective Reexports but I think that's for another day... :D

**Comment by bsermons** [comment]
Yea it alleviates the main pain I was having.  I'm not too concerned about showing some extra items in the completion list at this point either.  Thanks for the suggestions with the PR also!

**Comment by kRITZCREEK** [comment]
Thank you for fixing it in the first place! :+1:
