### ISSUE TITLE
Allow completions with empty search term when using filters.

### ISSUE THREAD

**Issue by bsermons** [kRITZCREEK/psc-ide#91]
When I try to filter by module with an empty search term I get 0 results:

For example:
Command:  {"command":"complete","params":{"filters":[{"filter":"modules","params":{"modules":["Halogen.HTML.Indexed"]}}],"matcher":{"matcher":"flex","params":{"search":""}}}}

Result: {"result":[],"resultType":"success"}

**Comment by kRITZCREEK** [comment]
The reason is that the flex matcher doesn't match anything on empty input. If you just remove the matcher from your request you should get all identifiers inside the module.

````json
{
  "command": "complete",
  "params": {
    "filters": [
      {
         "filter": "modules",
         "params":{"modules":["Halogen.HTML.Indexed"]}
       }
    ]
  }
}
```

**Comment by bsermons** [comment]
Thanks, that works great.  I'm fine with how it is, I just didn't realize how the matchers worked.
