### ISSUE TITLE
What is the purpose of load command?

### ISSUE THREAD

**Issue by user471** [kRITZCREEK/psc-ide#93]
Why cannot ```psc-ide``` load modules when it needs them?

For example, I want to get type of function ```map```
```
-- Main.purs
module Main where
import Prelude
x = map (+1) [1,2,3]
```
The command ```type``` could look like this
```
{
  "command": "type",
  "params": {
    "search": "map",
    "file": "Main.purs"
  }
}
```
and ```psc-ide``` could parse ```Main.purs``` file and load all modules from imports.
So, you don't need to manage loaded modules manually.

**Comment by kRITZCREEK** [comment]
I thought about that. That's a nice idea but currently psc-ide is using the purescript parser which only succeeds on syntactically correct files. This fails when you are in the middle of editing a file.

I'd love to implement this but we first need an import parser that ignores failures in the remaining file.

**Comment by user471** [comment]
>This fails when you are in the middle of editing a file.
I don't think It would be a big problem. ``psc-ide``` could use previous module list for the incorrect file.
And if you have added new imports you can just comment the broken code for a second.

**Comment by user471** [comment]
Also, some sort of ```autoload``` command would be useful.
```
{
  "command": "autoload",
  "params": {
    "file": "Main.purs"
  }
}
```
if ```file``` parameter is null then command will load all modules in project.

**Comment by kRITZCREEK** [comment]
> >This fails when you are in the middle of editing a file.

>And if you have added new imports you can just comment the broken code for a second.

Having to comment out code to parse the imports is not an acceptible solution. The need to scroll to the top of the file and add an import already breaks your workflow. If you now have to also make sure your file is syntactically correct you just lost your train of thought.

>I don't think It would be a big problem. ```psc-ide``` could use previous module list for the incorrect file.

I like to avoid caching as much as possible, so it would be a lot better if we wrote a parser that stopped after the import declarations. I don't think it's that hard of a problem.

**Comment by user471** [comment]
> If you now have to also make sure your file is syntactically correct you just lost your train of thought.
Yes, It isn't ideal. What editor do you use for haskell? In haskell-mode it works the same way. You need to recompile file to access some functionality. And after a while you get used to it.

**Comment by kRITZCREEK** [comment]
The problem with the autoload command is that there is no notion of a "project" in purescript yet. It's just a bunch of files.

The convention is to put these into bower_components and src but that's not a sufficient definition of a project so we'll have to either define a project format for psc-ide or wait a bit until we get the purescript package manager and a "real project format"

**Comment by kRITZCREEK** [comment]
I would actually prefer to use the new compiler functionality https://github.com/purescript/purescript/issues/1509 which would allow us to handle the imports for the user. Like a Java IDE. This would be the optimal solution in terms of flow

**Comment by user471** [comment]
>The convention is to put these into bower_components and src but that's not a sufficient definition of a project 
There could be new option for ```psc-ide-server```
```
--src "c:/project/bower_components/;c:/project/src/"
```

**Comment by kRITZCREEK** [comment]
The new workflow involves loading all the modules anyway.
