### ISSUE TITLE
psc-ide-server: Be able to provide non-default location to "output/" path

### ISSUE THREAD

**Issue by damncabbage** [kRITZCREEK/psc-ide#94]
It'd be lovely if we could specify the build-output directory; at the moment it's [unfortunately hardcoded](https://github.com/kRITZCREEK/psc-ide/blob/5790093d233f8ff03d94a6d96c2a0333bf50d960/server/Main.hs#L63) to whatever's given to `-d` plus `"output"/`.

(In my case, for example, I'm writing a library that's being built to `lib`, so that I can publish it on npm and have it look like any other library. I'm also working on something else that's building to `support/lib/`.)

PS: Thanks for writing this project. :smile:

**Comment by kRITZCREEK** [comment]
I just wanted to wait until someone needed it before making it configurable ;)

It gets even worse... it's hardcoded TWICE https://github.com/kRITZCREEK/psc-ide/blob/5790093d233f8ff03d94a6d96c2a0333bf50d960/src/PureScript/Ide.hs#L185

code:nose: :D

**Comment by damncabbage** [comment]
:heart_eyes:
